### ISSUE TITLE
update README.

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#159]
- [ ] rename README to ownCloud calendar or something similar
- [ ] add a screenshot
- [ ] add link to documentation
- [ ] add link to #ownCloud (for users) and #ownCloud-calendar (for developers) on free node

**Comment by georgehrke** [comment]
outsource `building js` and similar to the wiki

**Comment by aspdye** [comment]
I have already done this task for the ownCloud Core's README.md and I am going to do this for Calendar ;)

**Comment by georgehrke** [comment]
@aspdye Looking forward to it :)

**Comment by RealRancor** [comment]
Re-post from: https://github.com/owncloud/calendar/issues/1037#issuecomment-190285228

-> Make sure that the README.md contains the info that this is the repository of the new calendar app and that:

- issues within the CalDAV backend code should reported to core
- issues within the old calendar app shouldn't reported here

**Comment by aspdye** [comment]
Good call @RealRancor :rocket: 
Where should issues with the old calendar App be reported? @georgehrke

**Comment by georgehrke** [comment]
The old calendar will be unmaintained and not supported anymore

**Comment by aspdye** [comment]
#267

**Comment by qwerty123443** [comment]
the link for the old calendar in the readme still points to [https://github.com/owncloud/calendar](https://github.com/owncloud/calendar) while it should point to [https://github.com/owncloudarchive/calendar](https://github.com/owncloudarchive/calendar)

**Comment by aspdye** [comment]
@qwerty123443 Take a look into #267 ;) Links will be fixed there. I think there is no need to fix the README.md in the old "archive"-repositories for now - other things are more important now.
