### ISSUE TITLE
Consider dropping support for Safari

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#495]
Safari leaks support for quite a few things I would like to use:
- [ ] http://caniuse.com/#feat=download - Needed to have a better file name single event export, currently the uri is used
- [ ] http://caniuse.com/#feat=input-color - Needed for custom color picker, don't want to use js based color picker
- [ ] https://kangax.github.io/compat-table/es6/ generally a very bad ES 6 support

**Comment by georgehrke** [comment]
for the input color issue we could check if the browser supports it and don't show the input if it doesn't.

**Comment by georgehrke** [comment]
the download attribute will simply be ignored by Safari and all other browsers will have a fancy file name

ES6 support can actually wait a bit.
