### ISSUE TITLE
refactor .travis.yml

### ISSUE THREAD

**Issue by georgehrke** [owncloud/calendar#545]
Our `.travis.yml` is quite outdated and npm errors sometimes for unknown reasons.
We should try something similar to: https://github.com/owncloud/mail/blob/master/.travis.yml

There are a few things to discuss previously here:
- [ ] Does it make sense to test different DBs after all? We only use a database thru CalDAV and \OCP\Config but there aint any own sql requests.
- [ ] ...

**Comment by georgehrke** [comment]
cc @DeepDiver1975

**Comment by georgehrke** [comment]
- [x] finally include some JS test coverage (ref https://github.com/owncloud/calendar/issues/95)
- [ ] also test different browsers?
